zhihu/griffith

packages/griffith/package.json
packages/griffith/src/components/Player/Player.js
packages/griffith/src/components/PlayerContainer/PlayerContainer.js
packages/griffith/src/contexts/VideoSource/VideoSourceProvider.js
yarn.lock

- replace `bigscreen` with `isomorphic-bigscreen` which is safe for server-side use
- fix a bug where a player ref is missing
- fix a bug that fullscreen event listeners are mistakenly added to global. 
- remove a redundant `emitEvent` prop
Fixes #15

fix fullscreen related issues

---

package.json
packages/griffith-hls/package.json
packages/griffith-message/package.json
packages/griffith-mp4/package.json
packages/griffith-utils/package.json
packages/griffith/package.json

也可以利用 exec 来添加，但需要额外的 filter（scope/ignore） —— 如 `lerna exec --parallel --stream --scope griffith* --ignore griffith-standalone -- yarn build -w`
不如 run 直观，并且 standalone 有必要可以加不同的 watch script。

build: add `build:watch` script

---

.eslintignore
.prettierignore
package.json
packages/griffith-mp4/src/mse/controller.js

If the ```buffered``` has cache, we don't need to repeat request video data.

feat: add buffered cache

---

README-ja.md
README-zh-Hans.md
README.md

Should not use self-closing script tags

docs: script tag

---

example/webpack.config.js
package.json
packages/griffith-mp4/src/mp4/utils/getBufferStart.js
packages/griffith-mp4/src/mp4/utils/getFragmentPosition.js
packages/griffith-mp4/src/mse/controller.js

if the last GOP dont have audio track, we dont need append audio sourcebuffer.
for now, if we append audio sourcebuffer, we will get this error. see https://github.com/zhihu/griffith/issues/45

fix: last GOP dont have audio track

---

packages/griffith-mp4/src/mp4/mp4Probe.js
packages/griffith-mp4/src/mp4/utils/getSamplesInterval.js
packages/griffith-mp4/src/mse/controller.js

In some case, we have empty edit media time, If we dont ignore the empty edit media time, we will have audio/video sync problem. see https://github.com/zhihu/griffith/issues/14

fix: empty audio track

---

example/fmp4/index.js
example/hls/index.js
example/inline/index.js
example/main/index.js
example/mp4/index.js
example/package.json
packages/griffith-mp4/src/fetch.js
yarn.lock

```AbortController``` only support Chrome 66+, so we use xhr instead of the fetch api.

fix: use xhr instead of the fetch api

---

packages/griffith-mp4/src/mse/controller.js
packages/griffith-mp4/src/player.js

the media source read state is ended when we click replay button, so we cannot append new buffer to media source.
the solution is we append a empty buffer to sourcebuffer before we try click replay button or move the slider. then the media source read state will reopen. 
see https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/media-source/mediasource-append-buffer.html#L144

fix: replay case

---

packages/griffith-hls/src/Video.js
packages/griffith-hls/src/index.js
packages/griffith-mp4/src/index.js
packages/griffith/src/components/Video/NormalVideo.js
packages/griffith/src/components/Video/Video.js

使用 hls 插件的时候，外层不应该处理 src 改变的事件。
所以改变了一下插件的结构，这样 Video 判断是否需要跳过 src 改变时的相关逻辑
Fixes https://github.com/zhihu/griffith/issues/50

Fix a hls bug when switching quality

---

packages/griffith-hls/src/index.js
packages/griffith-mp4/src/index.js
packages/griffith-mp4/src/mse/controller.js
packages/griffith-mp4/src/player.js

we don't need to create a new MediaSource when the user switches video quality.
we remove the old buffer and append new video data When the user switches video quality.

feat: adjust video quality

---

packages/griffith-mp4/src/mp4/mp4Box.js

In some case, the hdlr box is not the first sub box of trak box.

fix: cannot read property hdlr of undefined

---

packages/griffith-mp4/src/fetch.js
packages/griffith-mp4/src/mse/controller.js

- Add Access-Control-Allow-Origin request header
- Fix `Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer is still processing an 'appendBuffer' or 'remove' operation.`
- Fix buffered cache bug

 fix: failed to execute appendBuffer on SourceBuffer

---

packages/griffith-mp4/src/mse/controller.js

- Fix `Failed to execute 'endOfStream' on 'MediaSource': The 'updating' attribute is true on one or more of this MediaSource's SourceBuffers.`

fix: failed to execute endOfStream on MediaSource

---

packages/griffith-mp4/src/mse/controller.js
packages/griffith-mp4/src/player.js

Use `buffered .start` when `buffered.length` is not empty
- Fix: `Failed to execute 'start' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0)`

fix: failed to execute start on TimeRanges

---

packages/griffith/src/components/Player/Player.js

If the user executes seek action when the fist frame is not ready, will throw some error.

fix: dont show Controller component when first frame is not ready

---

packages/griffith-mp4/src/mse/controller.js
packages/griffith-mp4/src/mse/polyfill.js

If SourceBuffer has too much data in it, calling SourceBuffer.appendBuffer() will trigger the following message in the Chrome console window.

fix: exceeding the buffering quota

---

packages/griffith-mp4/src/mp4/mp4Probe.js
packages/griffith-mp4/src/mse/controller.js
packages/griffith-mp4/src/player.js

don't use MSE If the video don't have a video track

fix: don't use MSE If the video don't have a video track

---

example/babel.config.js
example/package.json
example/webpack.config.js
package.json
packages/griffith-hls/package.json
packages/griffith-message/package.json
packages/griffith-mp4/package.json
packages/griffith-utils/package.json
packages/griffith/package.json
yarn.lock

- webpack 改为直接使用 package.json 的 source 字段解析 src 中的文件。这样开发的过程中不需要再起一个 watch。而且如果 webpack 使用 rollup 构建的文件会导致 source map 丢失，debug 不方便。
- 去掉 @zhihu/babel-preset

Example Build

---

packages/griffith-mp4/src/mse/controller.js

if we end of steam when the last GOP is not playing, the video duration will be changed, and the last GOP will not play ever.

fix: end of stream when last GOP is played

---

packages/griffith-mp4/src/mp4/utils/__tests__/getSamplesInterval.spec.js
packages/griffith-mp4/src/mp4/utils/getSamplesInterval.js
packages/griffith-mp4/src/mp4/utils/index.js

some video don't have B/P frame, we should make a fake GOP, then we can play it with streaming

fix: make a fake GOP when video dont have B/P frame

---

packages/griffith-mp4/src/mp4/mp4Probe.js
packages/griffith-mp4/src/mp4/utils/getFragmentPosition.js
packages/griffith-mp4/src/mse/controller.js
packages/griffith-mp4/src/player.js

close https://github.com/zhihu/griffith/issues/46

fix: cannot read property start of undefined

---

packages/griffith-mp4/src/fetch.js
packages/griffith-standalone/README-zh-Hans.md
packages/griffith-standalone/README.md

close https://github.com/zhihu/griffith/issues/90

fix: remove setRequestHeader

---

packages/griffith/src/components/Player/Player.js
packages/griffith/src/components/Video/Video.js

Mobile device use the browser's default video controls, we don't need to handle `onVolumeChange ` event

fix: mobile muted

---

packages/griffith/README-zh-Hans.md
packages/griffith/README.md
packages/griffith/index.d.ts
packages/griffith/src/components/PlayerContainer/PlayerContainer.js
packages/griffith/src/contexts/VideoSource/VideoSourceProvider.js

Add a optional prop `defaultQuality` to Griffith, which controls the default definition of a playing video.

feat: add defaultQuality prop

---

packages/griffith/src/components/Controller/styles.js

fix: time wrap

---

example/hls/App.js
packages/griffith-hls/src/Video.js
packages/griffith-hls/src/utils/__tests__/__snapshots__/createMasterM3U8.spec.js.snap
packages/griffith-hls/src/utils/__tests__/createMasterM3U8.spec.js
packages/griffith-mp4/src/player.js
packages/griffith/README-zh-Hans.md
packages/griffith/README.md
packages/griffith/src/components/Controller/items/__tests__/__snapshots__/CombinedTimeItem.spec.js.snap
packages/griffith/src/components/Player/Player.js
packages/griffith/src/components/PlayerContainer/PlayerContainer.js
packages/griffith/src/components/Video/NormalVideo.js
packages/griffith/src/contexts/VideoSource/VideoSourceProvider.js
packages/griffith/src/contexts/VideoSource/parsePlaylist.js

增加 `useAutoQuality` 属性，默认为 `false`
只有在 useAutoQuality 启用并且 source 没有提供 auto quality 时，hls 视频才会尝试本地手动生成 auto 质量（而且这个实现看起来有 BUG）
修改了 example 的 hls 页面

feat: use auto quality

---

example/hls/App.js
packages/griffith/README-zh-Hans.md
packages/griffith/README.md
packages/griffith/src/components/Controller/Controller.js
packages/griffith/src/components/Controller/styles.js
packages/griffith/src/components/Player/Player.js
packages/griffith/src/components/PlayerContainer/PlayerContainer.js

feat: hidden ui

---

packages/griffith/README-zh-Hans.md
packages/griffith/README.md
packages/griffith/src/components/Player/Player.js
packages/griffith/src/components/PlayerContainer/PlayerContainer.js

Autoplay is not always required muted.
Reference: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

feat: allow autoplay with sound

---

packages/griffith/package.json
packages/griffith/src/contexts/Position/PositionProvider.js
packages/griffith/src/utils/listenResize.js
yarn.lock

element-resize-event：
- 过时的库，当前已经不需要了（polyfill 其实也是多余的，相对于我们的覆盖范围，这个 PR 仍然加了是为了更好地兼容）
- 它内部有个非法模块格式使用 [exports.bind](https://github.com/KyleAMathews/element-resize-event/blob/master/index.js#L70)
看起来 resize 监听本身也可能是多余的，最好完全用 CSS 方案来替换。

refactor: prefer using native ResizeObserver

---

packages/griffith/package.json
packages/griffith/src/contexts/VideoSource/VideoSourceProvider.js
yarn.lock

节省几 K。
PS. 像旧的 history 会依赖它，但新版不会。建议使用标准化 URLSearchParams。
```js
├─┬ griffith@1.12.0
│ └── query-string@6.13.7 
├─┬ history@3.3.0
│ └── query-string@4.3.4  deduped
└── query-string@4.3.4 
```

chore: remove query-string

---

packages/griffith-message/README-zh-Hans.md
packages/griffith-message/README.md
packages/griffith-message/index.d.ts
packages/griffith-message/src/constants/events.js
packages/griffith/src/contexts/Message/MessageContext.js

增加一个 event，用以通知外界 actions 注册完毕

feat: add SUBSCRIPTION_READY event

---

packages/griffith/src/contexts/Message/MessageContext.js

之前的 onEvent 并没有真正 dispatch cross-window message，应该使用 emitEvent
前置 MR：https://github.com/zhihu/griffith/pull/196

fix: emit SUBSCRIPTION_READY

---

.github/workflows/main.yml

修复测试，griffith 包有一些互相依赖，link 指向的是构建后的文件，所以先构建再测试，见：https://github.com/zhihu/griffith/runs/3529866257

ci: run build before test

---

packages/griffith/src/components/Video.js

文件中错误添加了两个 handleError 方法，删除掉多余的。
TODO：这应该是由 lint 提示出来的。

fix: remove duplicate handleError in Video

---

.eslintrc.js
README-ja.md
README-zh-Hans.md
README.md
package.json

- 此配置自动解决了 tsconfig alias/extensions 问题：
https://github.com/import-js/eslint-plugin-import/blob/main/config/typescript.js
- 额外加了个 types badge
- 默认应当使用 --cache，25s 与 0.7s 的区别

chore: update eslint config

---

.eslintrc.js

- plugin:prettier 会引用 prettier
- Prettier plugin/extends 包含了禁用 @typescript-eslint 的风格部分，但这个依赖于定义顺序，如果有 overrides， 需要重新申明一次。

chore: use prettier plugin to override eslint config

---

packages/griffith/src/components/items/PlaybackRateMenuItem.tsx
packages/griffith/src/components/items/QualityMenuItem.tsx

当单独使用Controller组件时候会报错找不到倍速数组，因为相关组件是从Context取值，若单独只使用Controller，而没有提供Context就会报错找不到相应的值，因此增加判断没有倍速数组就不展示

fix: 修复controller取不到值的问题

---

packages/griffith/README-zh-Hans.md
packages/griffith/src/components/Player.tsx

目前现状：
standalone 模式下，接口中的 title 会覆盖 document.title
修改后：
添加 noWriteDocTitle 属性，业务控制是否使用 title 覆盖 document.title，默认值为 true，覆盖。
- [ x ] 自测通过

feat: 添加 noWriteDocTitle，控制是否使用 title 覆盖 document.title

---

packages/griffith/src/components/Player.tsx
packages/griffith/src/components/Video.tsx
packages/griffith/src/components/VideoWithMessage.tsx

修复 #234 Safari 中拖放滚动条可能造成 UI 卡住，loading 覆盖导致不能交互。
Safari 中 waiting 之后很可能不会触发 playing（即使处于播放中），但 waiting 之后一定会触发 canplay：
| Chrome |  Safari | 
| --- | --- |
| <img width="647" alt="onEvent eventdoncanplay (currentTie" src="https://user-images.githubusercontent.com/105919/150501973-ea314187-3864-4c34-b2c6-55e33760449c.png"> | <img width="638" alt="enEvent eventldomplsy (eurrentTine O, durat ion 182 234, error null)" src="https://user-images.githubusercontent.com/105919/150502035-79d3ec03-aafa-4f32-924b-6a112f3953de.png"> |

fix: fix loading state in Player

---

packages/griffith-utils/src/__tests__/ua.spec.ts
packages/griffith/src/components/Controller.tsx
packages/griffith/src/components/Player.tsx
packages/griffith/src/components/usePlayerShortcuts.ts
packages/griffith/src/utils/parseUA.ts

- 新增：**允许热键脱离 controller 使用**（迁在 Player 内更合适，但它太长，拆到单独文件里了）—— 例子，在主站的所有视频，还没有播放时没有显示 controller，这时无法使用任意热键，同样播放结束时 controller 也隐藏了，还有不加载 controller 的平板也能外接键盘
- 新增：将 Player 设置为可聚焦元素，这样即使 standalone=false 热键也能工作（对视频的任意操作都会聚焦到上面）—— standalone 看起来是个不恰当的属性，不正交，应当把它的行为拆开
- 修复：ua 中加了 ua 和 typeof 判断：#18 #158

feat: allow use shortcut keys without controller

---

packages/griffith/src/components/Slider.tsx
packages/griffith/src/components/usePlayerShortcuts.ts

预防热键绑定的事件被重复处理：线上 bug 表现，点击进度条（会聚焦到它上面），这时按上/下箭头，进度和音量同时被改变了（不同地方处理了两次）。
不仅是播放器本身，这也能防止与应用其他部分可能存在的冲突。

fix: do not process shortcut when event is default prevented

---

example/index.html
packages/griffith/src/components/Controller.styles.ts
packages/griffith/src/components/items/__tests__/__snapshots__/CombinedTimeItem.spec.tsx.snap

让时间显示不再抖动，案例见：https://www.zhihu.com/zvideo/1437261125772079104 —— 从 1s 开始当前时间就在抖。
[font-variant-numeric](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric) 在不变更字体的情况下，让数字有固定的尺寸 —— 对比 YouTube 视频时间不抖动的原因是因为它使用了定制字体（"YouTube Noto", Roboto）。

fix: use fixed size for time numbers

---

packages/griffith/src/components/Player.tsx

bug: 视频在loading状态下派发PAUSE action并不能暂停视频

fix: 修复loading状态下不能暂停的问题

---

packages/griffith/src/components/Player.tsx
packages/griffith/src/components/items/ControllerTooltip.tsx
packages/griffith/src/components/items/FullScreenButtonItem.tsx
packages/griffith/src/components/items/PageFullScreenButtonItem.tsx
packages/griffith/src/components/items/PipButtonItem.tsx
packages/griffith/src/components/items/PlayButtonItem.tsx
packages/griffith/src/components/items/__tests__/__snapshots__/FullScreenButtonItem.spec.tsx.snap
packages/griffith/src/components/items/__tests__/__snapshots__/PlayButtonItem.spec.tsx.snap
packages/griffith/src/components/usePlayerShortcuts.ts

feat: add hotkey t/p and tooltips

---

packages/griffith/README-zh-Hans.md
packages/griffith/README.md
packages/griffith/src/components/Player.tsx
packages/griffith/src/components/items/QualityMenuItem.tsx
packages/griffith/src/contexts/VideoSourceProvider.tsx
packages/griffith/src/contexts/parsePlaylist.ts
packages/griffith/src/types.ts

default rule of qualities is ['auto', 'ld', 'sd', 'hd', 'fhd']，allow reverse when decQualities = true

feat: add defaultQualityOrder prop

---

packages/griffith/src/components/Player.tsx
packages/griffith/src/utils/pip.ts

多播放器场景会共用一个 Pip 实例，只有第一个播放器能才能正常 init
需要在组件内部执行 new Pip()

fix: 多个播放器使用同一个 Pip 实例问题修复

---

packages/griffith-message/README-zh-Hans.md
packages/griffith-message/README.md
packages/griffith-message/src/constants/events.ts
packages/griffith/src/components/VideoWithMessage.tsx

Add `videoWidth` and `videoHeight` properties to events payload.

chore: add video size for events payload

---

example/src/MP4Page.tsx
packages/griffith/src/components/Player.tsx
packages/griffith/src/components/Video.tsx

提供能够透传 video 原生属性 crossorigin 的能力

feat: 透传 video 标签 crossorigin
