- README-zh_CN.md
- README.md
> docs: update badge

- README.md
Some tiny grammar flaws are fixed.
> docs: grammar check

- packages/griffith-mp4/src/mse/controller.js
- packages/griffith-mp4/src/player.js
- fix: mediaSource.endOfStream() Throws error
- fix: SourceBuffer has been removed
> fix: some MSE error

- .travis.yml
- CONTRIBUTING-zh_CN.md
- CONTRIBUTING.md
- package.json
> fix: ci config

- packages/griffith/package.json
Fixes # https://github.com/zhihu/griffith/issues/24
> fix: Module not found

- example/package.json
- packages/griffith-hls/package.json
- packages/griffith/README-zh_CN.md
- packages/griffith/README.md
- yarn.lock
fix ```hls.js``` dependencies problem
> fix: hls dependencies

- packages/griffith-standalone/src/index.js
> fix: standalone build

- README-ja_JP.md
- README-zh_CN.md
- README.md
Add a  Japanese version of the main README file.
> docs: japanese version

- README-ja_JP.md
> docs: polish grammar

- packages/griffith-standalone/src/index.js
> Revert "fix: standalone build"

- packages/griffith-mp4/src/mse/controller.js
Fixes https://github.com/zhihu/griffith/issues/47
> fix:  Cannot read property appendBuffer of undefined

- packages/griffith-mp4/src/mse/controller.js
see https://stackoverflow.com/a/21249496
> fix: failed to execute appendBuffer on SourceBuffer

- packages/griffith-mp4/src/mse/controller.js
use `currentTime` to confirm if we dont need to request video data
> fix: cache data

- packages/griffith-mp4/src/mse/controller.js
No need to use mseUpdating flag
> fix: remove mseUpdating flag

- packages/griffith-mp4/src/fetch.js
> fix: add Access-Control-Allow-Methods limit

- packages/griffith-mp4/src/mp4/mp4Box.js
> fix: cannot read property handlerType of undefined

- .eslintrc.js
- .travis.yml
- package.json
- packages/griffith-standalone/package.json
- yarn.lock
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> optimize ci

- example/mp4/App.js
- packages/griffith/README-zh-Hans.md
- packages/griffith/README.md
- packages/griffith/src/components/Player/Player.js
- packages/griffith/src/components/PlayerContainer/PlayerContainer.js
- website/package.json
- yarn.lock
add muted autoplay feature
close https://github.com/zhihu/griffith/issues/62
> feat: add muted autoplay

- .travis.yml
- example/package.json
- package.json
- packages/griffith-standalone/package.json
- website/gatsby-config.js
- website/package.json
- yarn.lock
> docs: publish gatsby website

- CHANGELOG.md
- example/CHANGELOG.md
- example/package.json
- lerna.json
- packages/griffith-mp4/CHANGELOG.md
- packages/griffith-mp4/package.json
- packages/griffith-standalone/CHANGELOG.md
- packages/griffith-standalone/package.json
- packages/griffith/CHANGELOG.md
- packages/griffith/package.json
- packages/griffith/src/components/Controller/Controller.js
- packages/griffith/src/index.js
- website/CHANGELOG.md
- website/package.json
> fix: export controller component

- package.json
- yarn.lock
[kind-of bug](https://github.com/advisories/GHSA-6c8f-qphg-qjgp)
development is well
> fix: kind-of bug

- example/iframe/index.html
- example/iframe/index.js
- packages/griffith-message/README-zh-Hans.md
- packages/griffith-message/README.md
- packages/griffith-message/src/constants/actions.js
- packages/griffith/src/components/Player/Player.js
> feat: update action message

- packages/griffith/src/components/Player/Player.js
- packages/griffith/src/components/ProgressDot/ProgressDot.js
- packages/griffith/src/components/ProgressDot/styles.js
- packages/griffith/src/components/Timeline/MinimalTimeline.js
1. 修正节点位置
2. mini模式下进度条添加 progressDots属性
> fix: fix the position of the node & add progressDots in minimalTimeline

- example/package.json
- packages/griffith-hls/package.json
- packages/griffith-mp4/package.json
- packages/griffith-standalone/package.json
- packages/griffith/package.json
- website/package.json
- yarn.lock
修正版本范围：允许在项目内使用 hooks，允许使用 React 17（仅有 jsx transform 变化）
> chore: update version range of React

- packages/griffith/README.md
- packages/griffith/index.d.ts
- packages/griffith/src/components/Player/Player.js
- packages/griffith/src/components/PlayerContainer/PlayerContainer.js
expose onFullScreenChange event to outside.
> feat: expose onFullScreenChange event

- example/src/IframePage.jsx
- packages/griffith-message/README-zh-Hans.md
- packages/griffith-message/README.md
- packages/griffith-message/index.d.ts
- packages/griffith-message/src/constants/actions.js
- packages/griffith-message/src/constants/events.js
- packages/griffith/src/components/Controller/Controller.js
- packages/griffith/src/components/Player/Player.js
- packages/griffith/src/components/ProgressDot/ProgressDot.js
- packages/griffith/src/components/Slider/Slider.js
- packages/griffith/src/components/Timeline/Timeline.js
- packages/griffith/src/components/Timeline/__tests__/Timeline.spec.js
- packages/griffith/src/components/Timeline/__tests__/__snapshots__/Timeline.spec.js.snap
- packages/griffith/src/components/Timeline/styles.js
增加播放器 Controller 控件和播放节点 ProgressDot 的相关 event 和 action，以实现跨窗口通信
- SHOW_CONTROLLER，展示 Controller （event & action）
- HIDE_CONTROLLER，隐藏 Controller (event)
- HOVER_PROGRESS_DOT，鼠标 hover 播放节点（event）
- LEAVE_PROGRESS_DOT，鼠标离开播放节点（event）
hover ProgressDot 播放节点时进度条高度增加至 6px
> feat: add Controller & ProgressDot event

- packages/griffith/src/components/ProgressDot/ProgressDot.js
- packages/griffith/src/components/ProgressDot/styles.js
- packages/griffith/src/components/Timeline/styles.js
- fix TypeError: MinimalTimeline 没有不会传入 onProgressDotHover
- hover 播放节点时节点变高而不是进度条变高
- ProgressDot 两边增加透明的部分
> fix: type error & css

- example/src/IframePage.tsx
- packages/griffith-message/README-zh-Hans.md
- packages/griffith-message/README.md
- packages/griffith/src/components/Player/Player.js
支持 message 中的  ACTIONS.PLAYER.SET_VOLUME，更新文档
> feat: support action set_volume

- packages/griffith/index.d.ts
#97 #113 #126 #149 
TODO：还是全部迁移到 TS 更好。
> fix: fix some typing

- package.json
- scripts/wait-on-build.js
- yarn.lock
避免同时启动两个脚本（example server, build watch），现时防止文件还没构建好 server 启动出错。
> build: fix start script, wait for build files

- packages/griffith/src/components/PlayerContainer/PlayerContainer.js
- packages/griffith/src/constants/locales.js
- packages/griffith/src/contexts/Locale/LocaleContext.js
- packages/griffith/src/contexts/Locale/LocaleProvider.js
修复 #194 带来的测试挂了的问题：snapshot 测试单组件文件引入 Context，但没有默认值，直接出错。
TODO：应该让 CI 跑起来。
> fix: fix default value in LocaleContext

- jest.config.base.js
- packages/griffith-hls/src/utils/__tests__/getMasterM3U8Blob.spec.js
- packages/griffith-message/src/__test__/constants.spec.ts
- packages/griffith-message/src/__test__/createMessageHelper.spec.ts
- packages/griffith-utils/src/__tests__/isHlsNativeSupported.spec.ts
- packages/griffith-utils/src/__tests__/isMSESupported.spec.ts
> test: add more tests

- packages/griffith/src/components/Controller.tsx
> fix: 撤销网页全屏按钮

- packages/griffith/src/components/Controller.tsx
删除倍速按钮,
原因： 选择倍速后切换清晰度，倍速还原了，先下掉倍速按钮
> chore: 删除倍速按钮

- packages/griffith/src/components/Controller.styles.ts
- packages/griffith/src/components/Controller.tsx
- packages/griffith/src/components/items/CombinedTimeItem.tsx
- packages/griffith/src/components/items/ControllerButton.tsx
- packages/griffith/src/components/items/FullScreenButtonItem.tsx
- packages/griffith/src/components/items/PageFullScreenButtonItem.tsx
- packages/griffith/src/components/items/PipButtonItem.tsx
- packages/griffith/src/components/items/PlayButtonItem.tsx
- packages/griffith/src/components/items/PlaybackRateMenuItem.tsx
- packages/griffith/src/components/items/QualityMenuItem.tsx
- packages/griffith/src/components/items/VolumeItem.tsx
- packages/griffith/src/components/items/__tests__/ControllerButton.spec.tsx
- packages/griffith/src/components/items/__tests__/__snapshots__/CombinedTimeItem.spec.tsx.snap
- packages/griffith/src/components/items/__tests__/__snapshots__/FullScreenButtonItem.spec.tsx.snap
- packages/griffith/src/components/items/__tests__/__snapshots__/PlayButtonItem.spec.tsx.snap
- packages/griffith/src/components/items/__tests__/__snapshots__/VolumeItem.spec.tsx.snap
> fix: use shared ControllerButton, prevent submitting form

- packages/griffith/src/components/Player.styles.ts
- packages/griffith/src/components/Player.tsx
- packages/griffith/src/constants/locales.ts
> fix: add replay to locales

- .eslintrc.js
- example/vite.config.js
- packages/griffith/src/components/Loader.tsx
- packages/griffith/src/components/Timeline.tsx
- packages/griffith/src/components/Tooltip.tsx
- packages/griffith/src/components/VolumeSlider.tsx
- packages/griffith/src/components/items/TimelineItem.tsx
- packages/griffith/src/hooks/useBoolean.ts
- tsconfig.json
- Timeline 改用 hooks
- 示例中改用 tsconfig-paths 加载 alias，这样比较简单且自动化（这也是 eslint-plugin-import 使用的）
> refactor: use hooks in Timeline, add useBoolean

- example/src/MP4Page.tsx
- packages/griffith/package.json
- packages/griffith/src/components/Controller.styles.ts
- packages/griffith/src/components/Controller.tsx
- packages/griffith/src/components/Player.tsx
- packages/griffith/src/components/Timeline.styles.ts
- packages/griffith/src/components/TranslatedText.tsx
- packages/griffith/src/components/Video.tsx
- packages/griffith/src/components/__tests__/__snapshots__/MinimalTimeline.spec.tsx.snap
- packages/griffith/src/components/items/PageFullScreenButtonItem.tsx
- packages/griffith/src/components/items/QualityMenuItem.tsx
- packages/griffith/src/components/items/__tests__/__snapshots__/TimelineItem.spec.tsx.snap
- packages/griffith/src/constants/KeyCode.ts
- packages/griffith/src/constants/locales.ts
1.修复一些样式问题
2.设置默认隐藏网页全屏
3.修复切换清晰度后倍速还原的问题
4.优化清晰度按钮文案展示
> feat: 修复 UI 样式以及增加 `shouldShowPageFullScreenButton` prop

- packages/griffith/src/components/Controller.styles.ts
https://codesandbox.io/s/griffith-forked-oxi96?file=/src/index.js:246-294
- [x ] I have commented my code, particularly in hard-to-understand areas
> fix: time box-sizing

- packages/griffith/src/components/Player.tsx
- packages/griffith/src/components/Video.tsx
- packages/griffith/src/types.ts
内部 Video 参数及类型优化：如果事件（参数）使用与原生不一样，就不使用原生名称，防止误解。
> refactor: distinguish native/custom event props in Video

- example/src/App.tsx
- example/src/HLSPage.tsx
- example/src/MP4Page.tsx
- packages/griffith/src/components/Player.tsx
- packages/griffith/src/contexts/VideoSourceContext.ts
- packages/griffith/src/contexts/VideoSourceProvider.tsx
- packages/griffith/src/hooks/useChanged.ts
- 允许动态变更 `sources` 参数，解决 #108
- VideoSourceProvider 重构为 hooks，有效 memo、响应变化
> feat: allow change sources on the fly, refactor VideoSourceProvider

- packages/griffith/src/components/ActionToast.tsx
- packages/griffith/src/components/Controller.tsx
- packages/griffith/src/components/Player.styles.ts
- packages/griffith/src/components/Player.tsx
- packages/griffith/src/components/VolumeSlider.tsx
- packages/griffith/src/components/items/VolumeItem.tsx
解决 #225
- 将操作反馈独立出来，可以简化很多 Player 与 Controller 的逻辑。
- 进度热键在 Controller 不显示时也应该工作，当前鼠标移出播放器就不工作了（TODO: 不 mount Controller 也应该工作，键盘操作是通用的，独立的）
> feat: add ActionToast for shortcut keys

- packages/griffith/src/components/Controller.tsx
- packages/griffith/src/components/Player.styles.ts
- packages/griffith/src/contexts/VideoSourceContext.ts
- packages/griffith/src/contexts/VideoSourceProvider.tsx
> feat: add shortcut keys for playback rate

- packages/griffith/src/components/ActionToast.tsx
- packages/griffith/src/components/Player.styles.ts
- packages/griffith/src/components/usePlayerShortcuts.ts
> fix: do not process shortcut in input fields

- packages/griffith/src/components/Slider.tsx
- packages/griffith/src/components/Video.tsx
- packages/griffith/src/components/__tests__/__snapshots__/MinimalTimeline.spec.tsx.snap
- packages/griffith/src/components/__tests__/__snapshots__/VolumeSlide.spec.tsx.snap
- packages/griffith/src/components/items/__tests__/__snapshots__/TimelineItem.spec.tsx.snap
- packages/griffith/src/components/items/__tests__/__snapshots__/VolumeItem.spec.tsx.snap
使用平滑进度更新（必须使用 CSS transform，不然会移动一下卡一下），对比：
https://user-images.githubusercontent.com/105919/152960312-233ff15a-8223-4589-98dc-7695ff764ed2.mov
https://user-images.githubusercontent.com/105919/152960094-4a775284-86a4-415a-b37e-417d025182c2.mov
> fix: use smooth progress transition

- packages/griffith/src/components/Player.tsx
> feat: 播放器中使用 Layer 定位

- example/src/App.tsx
- example/src/MP4Page.tsx
- packages/griffith/src/components/Player.tsx
- 监听函数一直是旧的，状态更新后函数内 state 为旧值（如：example 里面的按钮功能无法工作）
- source 修改时重置进度条
- run example
> fix: source change & handler error

- packages/griffith/src/components/items/ControllerTooltip.tsx
在ssr的时候会出现document.body为null的情况导致报错
> fix: 修改document.body=null的情况

- packages/griffith-message/src/constants/events.ts
- packages/griffith/src/components/VideoWithMessage.tsx
增加一个 loadeddata event 用于监听播放器首帧加载完成事件
> chore: add loadeddata event

- packages/griffith-hls/src/VideoComponent.tsx
- packages/griffith/src/components/Player.tsx
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> fix: Failed switch hls video

- packages/griffith/src/components/items/PipButtonItem.tsx
> fix: fix the hotkey tooltip of pip

- packages/griffith/src/contexts/VideoSourceProvider.tsx
Fix：DefaultQuality is assigned, but it is not in the quality list of that video
> fix: no defaultQuality in qualities

- packages/griffith-message/src/constants/events.ts
- packages/griffith/src/components/VideoWithMessage.tsx
Add support for progress event in griffith player and griffith-message
> chore: add player progress event

- packages/griffith/README-zh-Hans.md
- packages/griffith/README.md
- packages/griffith/src/components/Player.tsx
need a param to control the ablity of cross-window singlely
> feat: enableCrossWindowMessage split away from standalone
